import type { Metadata } from 'next'
import './globals.css'
import { Provider } from '@/src/components/ui/provider'

export const metadata: Metadata = {
  title: 'Cappuccino',
  description: 'Generated by create next app',
}



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html suppressHydrationWarning>
      <body>
        <Provider themes={['dark']}>{children}</Provider>
      </body>
    </html>
  )
}
